import { z } from 'zod';

import { REPLAY_POLICIES } from '@arthome/core';
import {
  DateIdSchema,
  InstantIn,
  ShowIdSchema,
  VenueIdSchema,
  vocabularyIn,
} from '@arthome/core/schema';

/** The `uint32` ceiling `DateScheduled.replay_window_hours` imposes. */
const UINT32_MAX = 2 ** 32 - 1;

/** The studio's `createDateDraft` (openapi/studio.yaml), minus the channel, which is the path. */
export const DraftDateSchema = z.strictObject({
  /** Generated by the client, so a draft can be saved before any round trip. */
  dateId: DateIdSchema,
  showId: ShowIdSchema,
  venueId: VenueIdSchema,
  startsAt: InstantIn,
  /** Chosen at creation because the public price depends on it; `none` is final. */
  replayPolicy: vocabularyIn(REPLAY_POLICIES),
  replayWindowHours: z.int().min(0).max(UINT32_MAX).nullable().default(null),
});

export type DraftDateBody = z.infer<typeof DraftDateSchema>;
