import { Column, CreateDateColumn, Entity, PrimaryColumn, UpdateDateColumn } from 'typeorm';

import type { DateOutcome, ReplayPolicy, TerritoryRights } from '@arthome/core';

/** data-model.md §2.2's `Date`, named apart from the global it would shadow. */
@Entity('date')
export class PerformanceDate {
  /** UUIDv7 generated by the client, and the key of `arthome.catalog.date`. */
  @PrimaryColumn('uuid')
  id!: string;

  @Column('uuid')
  show_id!: string;

  @Column('uuid')
  venue_id!: string;

  @Column('text')
  channel_id!: string;

  @Column('timestamptz')
  starts_at!: Date;

  /** Copied from the show; it freezes at publication (§2.2). */
  @Column('integer')
  runtime_min!: number;

  @Column('text')
  replay_policy!: ReplayPolicy;

  @Column('integer', { nullable: true })
  replay_window_hours!: number | null;

  @Column('jsonb')
  rights!: TerritoryRights;

  /**
   * Its day at the venue, unique within its show, set at publication (§2.7, D-075). A
   * postponement to another day takes that day's, the former one resolving for a month.
   */
  @Column('text', { nullable: true })
  slug!: string | null;

  /** At most `POSTPONEMENTS_MAX` (D-076). */
  @Column('integer', { default: 0 })
  postponements!: number;

  /** A fact, never rewritten nor erased (§2.2). */
  @Column('text', { nullable: true })
  outcome!: DateOutcome | null;

  /** Where a postponement moved the date: `starts_at` took this value in the same act. */
  @Column('timestamptz', { nullable: true })
  rescheduled_to!: Date | null;

  @Column('timestamptz', { nullable: true })
  outcome_declared_at!: Date | null;

  /** The run desk's message: content, in the language it was written in. */
  @Column('jsonb', { nullable: true })
  outcome_message!: { readonly contentLanguage: string; readonly text: string } | null;

  @CreateDateColumn({ type: 'timestamptz' })
  created_at!: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updated_at!: Date;
}
