import { Column, CreateDateColumn, Entity, PrimaryColumn, UpdateDateColumn } from 'typeorm';

import type { ReplayPolicy, TerritoryRights } from '@arthome/core';

/** data-model.md §2.2's `Date`, named apart from the global it would shadow. */
@Entity('date')
export class PerformanceDate {
  /** UUIDv7 generated by the client, and the key of `arthome.catalog.date`. */
  @PrimaryColumn('uuid')
  id!: string;

  @Column('uuid')
  show_id!: string;

  @Column('uuid')
  venue_id!: string;

  @Column('text')
  channel_id!: string;

  @Column('timestamptz')
  starts_at!: Date;

  /** Copied from the show; it freezes at publication (§2.2). */
  @Column('integer')
  runtime_min!: number;

  @Column('text')
  replay_policy!: ReplayPolicy;

  @Column('integer', { nullable: true })
  replay_window_hours!: number | null;

  @Column('jsonb')
  rights!: TerritoryRights;

  @CreateDateColumn({ type: 'timestamptz' })
  created_at!: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updated_at!: Date;
}
