import { Column, CreateDateColumn, Entity, PrimaryColumn, UpdateDateColumn } from 'typeorm';

import type { DateOutcome, PriceTier } from '@arthome/core';

export interface PriceTierColumn {
  readonly tier: PriceTier;
  readonly amountMinor: number;
  readonly currencyCode: string;
  readonly active: boolean;
}

export interface CapacityTierColumn {
  readonly id: string;
  readonly capacity: number;
  readonly openedAt: string;
}

/** The `DateSales` aggregate's row; its writes are conditioned on `version`. */
@Entity('date_sales')
export class DateSalesRow {
  /** The date's id, catalog's, and the key of `arthome.ticketing.date_sales`. */
  @PrimaryColumn('uuid')
  date_id!: string;

  @Column('text')
  channel_id!: string;

  @Column('integer')
  capacity_total!: number;

  @Column('integer', { nullable: true })
  provisioned_capacity!: number | null;

  @Column('jsonb')
  capacity_tiers!: CapacityTierColumn[];

  @Column('integer')
  seats_available!: number;

  @Column('integer')
  seats_sold!: number;

  @Column('integer')
  waitlist_count!: number;

  @Column('jsonb')
  price_tiers!: PriceTierColumn[];

  @Column('timestamptz', { nullable: true })
  prices_locked_at!: Date | null;

  @Column('timestamptz', { nullable: true })
  sales_closed_at!: Date | null;

  @Column('timestamptz', { nullable: true })
  sales_end_at!: Date | null;

  /**
   * Generated by Postgres from the two instants above, the expression in the migration alone: what
   *   the hot decrement's WHERE reads (adr-ticketing.md §2).
   */
  @Column({ type: 'boolean', insert: false, update: false })
  on_sale!: boolean;

  @Column('timestamptz', { nullable: true })
  starts_at!: Date | null;

  @Column('timestamptz', { nullable: true })
  schedule_stated_at!: Date | null;

  @Column('text', { nullable: true })
  outcome!: DateOutcome | null;

  @Column('timestamptz', { nullable: true })
  outcome_stated_at!: Date | null;

  @Column('integer')
  version!: number;

  /**
   * Counts the moves of what `availability_changed` carries, each counted in the statement that
   *   makes it; the publisher is due once it has published fewer. Postgres's `bigint`, read as text.
   */
  @Column({ type: 'bigint', insert: false, update: false })
  availability_moves!: string;

  @CreateDateColumn({ type: 'timestamptz' })
  created_at!: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updated_at!: Date;
}
