import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { HostTree } from '@angular-devkit/schematics';
import { SchematicTestRunner, UnitTestTree } from '@angular-devkit/schematics/testing';

const REPOSITORY_ROOT = fileURLToPath(new URL('../../../../', import.meta.url));
const COLLECTION = fileURLToPath(new URL('../../collection.json', import.meta.url));

/**
 * What the generators read or edit: the sibling manifests and sources (their consumer groups), the
 *   infra files, the tools, the docs.
 */
const SEEDED = [
  'README.md',
  'AGENTS.md',
  'apps/*/package.json',
  'apps/*/.env.example',
  'apps/*/src/*.ts',
  'infra',
  'tools/ops-check.mjs',
  'tools/purge-retention.mjs',
  'tools/republish-outbox.mjs',
  'libs/messaging/src/connector-config.spec.ts',
];

/**
 * A tree holding the committed files a generator reads, as the working copy has them. Committed
 *   only: a service generated by hand beside the tests would otherwise collide with theirs.
 */
export function repositoryTree(): UnitTestTree {
  const tree = new UnitTestTree(new HostTree());
  const tracked = execFileSync('git', ['ls-files', '-z', '--', ...SEEDED], {
    cwd: REPOSITORY_ROOT,
    encoding: 'utf8',
  })
    .split('\0')
    .filter((path) => path !== '');
  for (const path of tracked) tree.create(`/${path}`, readFileSync(join(REPOSITORY_ROOT, path)));
  return tree;
}

/** A generator run formats every file it touches, the first with Prettier cold. */
export const RUN_MS = 60_000;

/** The service the specs generate: its name and port are no committed service's. */
export const LIGHTING = {
  name: 'lighting',
  port: 3999,
  topics: 'rig:3,cue:6',
  consumer: true,
  sweeper: true,
  skipInstall: true,
};

export function testRunner(): SchematicTestRunner {
  return new SchematicTestRunner('@arthome-platform/schematics', COLLECTION);
}
